### ISSUE TITLE
missing files for processing data

### ISSUE THREAD

**Issue by hbaniecki** [Henrymachiyu/ProtoViT#2]
Hi, in README there are three files listed that are missing in the source code:
```bash
python scripts/crop_images.py
python scripts/split_dataset.py
python img_aug.py
```

**Comment by Henrymachiyu** [comment]
For crop_images and split_dataset file, I was mean to let user to use their own code, since it is more relevant to the data instead of the model. But I can provide the version of the cropping and split I used.
